export enum LOCALE_CALENDARS {
  buddhist = 'buddhist',
  chinese = 'chinese',
  coptic = 'coptic',
  dangi = 'dangi',
  ethioaa = 'ethioaa',
  ethiopic = 'ethiopic',
  gregory = 'gregory',
  hebrew = 'hebrew',
  indian = 'indian',
  islamic = 'islamic',
  islamicUmalqura = 'islamic-umalqura',
  islamicTbla = 'islamic-tbla',
  islamicCivil = 'islamic-civil',
  islamicRgsa = 'islamic-rgsa',
  iso8601 = 'iso8601',
  japanese = 'japanese',
  persian = 'persian',
  roc = 'roc',
}
